name: BlockSumo
version: 0.2
author: Nixuge
main: me.nixuge.BlockSumo
commands:
  join_blocksumo:
    description: join the blocksumo queue
    usage: /join_blocksumo
  end_blocksumo:
    description: force end the blocksumo /!\DEV ONLY/!\
    usage: /end_blocksumo
  start_blocksumo:
    description: force start the blocksumo /!\DEV ONLY/!\
    usage: /start_blocksumo
  kit:
    description: Change your kit
    usage: /kit
  testcommand:
    description: test command used for various purposes while testing
    usage: /testcommand
  test2:
    description: test command used for various purposes while testing
    usage: /test2